import {
  NAV_ITEM_TYPE_COLLAPSE,
  NAV_ITEM_TYPE_ITEM,
  NAV_ITEM_TYPE_TITLE,
} from '@/constants/navigation.constant'
import {
  Box,
  Calendar,
  Chart2,
  Cut,
  DocumentFilter,
  DocumentText,
  Educare,
  Home,
  Profile2User,
  RulerPen,
  Scan,
  Setting3,
  Wallet1,
} from 'iconsax-react'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
  {
    key: 'dashboard',
    path: '/dashboard',
    title: 'Dashboard',
    translateKey: 'nav.dashboard',
    icon: () => <Home color="currentColor" size="24" variant="Bulk" />,
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: 'schedule',
    path: '/schedule',
    title: 'Schedule',
    translateKey: 'nav.schedule',
    icon: () => <Calendar color="currentColor" size="24" variant="Bulk" />,
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: 'attendance',
    path: '',
    title: 'Attendance',
    translateKey: 'nav.attendance',
    icon: () => <Scan color="currentColor" size="24" variant="Bulk" />,
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: 'checkin',
        path: '/attendance/checkin',
        title: 'Check in',
        translateKey: 'nav.checkin',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'checkout',
        path: '/attendance/checkout',
        title: 'Check out',
        translateKey: 'nav.checkout',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'history',
        path: '/attendance/history',
        title: 'History',
        translateKey: 'nav.history',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: 'class',
    path: '/class/schedule',
    title: 'Class',
    translateKey: 'nav.class',
    icon: () => <Educare color="currentColor" size="24" variant="Bulk" />,
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: 'members',
    path: '/members',
    title: 'Members',
    translateKey: 'nav.members',
    icon: () => <Profile2User color="currentColor" size="24" variant="Bulk" />,
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: 'cuttingSessions',
    path: '/cutting-sessions',
    title: 'Cutting Session',
    translateKey: 'nav.cuttingSessions',
    icon: () => <Cut color="currentColor" size="24" variant="Bulk" />,
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: 'measurement',
    path: '/measurement',
    title: 'Measurement',
    translateKey: 'nav.measurement',
    icon: () => <RulerPen color="currentColor" size="24" variant="Bulk" />,
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: 'masters',
    path: '',
    title: 'Masters',
    translateKey: 'masters',
    icon: () => <Wallet1 color="currentColor" size="24" variant="Bulk" />,
    type: NAV_ITEM_TYPE_TITLE,
    authority: [],
    subMenu: [
      {
        key: 'sales',
        path: '/sales',
        title: 'Sales',
        translateKey: 'nav.sales',
        type: NAV_ITEM_TYPE_ITEM,
        icon: () => <Chart2 color="currentColor" size="24" variant="Bulk" />,
        authority: [],
        subMenu: [],
      },
      {
        key: 'packages',
        path: '/packages/membership',
        title: 'Packages',
        translateKey: 'nav.packages',
        type: NAV_ITEM_TYPE_ITEM,
        icon: () => (
          <DocumentFilter color="currentColor" size="24" variant="Bulk" />
        ),
        authority: [],
        subMenu: [],
      },
      {
        key: 'products',
        path: '/products',
        title: 'Products',
        translateKey: 'nav.products',
        type: NAV_ITEM_TYPE_ITEM,
        icon: () => <Box color="currentColor" size="24" variant="Bulk" />,
        authority: [],
        subMenu: [],
      },
      {
        key: 'finance',
        path: '/finance/rekening',
        title: 'Finance',
        translateKey: 'nav.finance',
        type: NAV_ITEM_TYPE_ITEM,
        icon: () => <Wallet1 color="currentColor" size="24" variant="Bulk" />,
        authority: [],
        subMenu: [],
      },
      {
        key: 'employee',
        path: '/employee',
        title: 'Employee',
        translateKey: 'nav.employee',
        type: NAV_ITEM_TYPE_ITEM,
        icon: () => (
          <Profile2User color="currentColor" size="24" variant="Bulk" />
        ),
        authority: [],
        subMenu: [],
      },
      {
        key: 'reports',
        path: '/reports',
        title: 'Reports',
        translateKey: 'nav.reports',
        type: NAV_ITEM_TYPE_ITEM,
        icon: () => (
          <DocumentText color="currentColor" size="24" variant="Bulk" />
        ),
        authority: [],
        subMenu: [],
      },
      {
        key: 'settings',
        path: '/settings',
        title: 'Settings',
        translateKey: 'nav.settings',
        type: NAV_ITEM_TYPE_COLLAPSE,
        icon: () => <Setting3 color="currentColor" size="24" variant="Bulk" />,
        authority: [],
        subMenu: [
          {
            key: 'rolesPermissions',
            path: '/settings/roles-permissions',
            title: 'Roles & Permissions',
            translateKey: 'nav.rolesPermissions',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: 'gymSetting',
            path: '/settings/gym/about',
            title: 'Gym',
            translateKey: 'nav.gymSetting',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: 'othersSetting',
            path: '/settings/others/commission',
            title: 'Others',
            translateKey: 'nav.othersSetting',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: 'logActivity',
            path: '/settings/log-activity',
            title: 'Log activity',
            translateKey: 'nav.logActivity',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
        ],
      },
    ],
  },
]

export default navigationConfig
